# Generated by Django 5.0.4 on 2024-04-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('post', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=200)),
            ],
        ),
    ]
