# Generated by Django 5.0.4 on 2024-04-17 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
